plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.13'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.pgsg'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven {
		url = uri("https://maven.pkg.github.com/89-49/common")
		credentials {
			username = findProperty('gpr.user') ?: System.getenv('GPR_USER')
			password = findProperty('gpr.token') ?: System.getenv('GPR_TOKEN')
		}
	}
}

ext {
	set('springCloudVersion', "2025.0.2")
}

dependencies {

	// Database
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'com.h2database:h2'

	// common 공통 모듈
	implementation 'org.pgsg:common:0.3.2-SNAPSHOT'

	// STOMP WebSocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	// QueryDSL
	annotationProcessor 'io.github.openfeign.querydsl:querydsl-apt:6.8:jpa'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'



	// test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

def querydslDir = layout.buildDirectory.dir("generated/querydsl").get().asFile

sourceSets {
	main.java.srcDirs += [ querydslDir ]
}


tasks.withType(JavaCompile).configureEach {
	options.getGeneratedSourceOutputDirectory().set(querydslDir)
}

clean {
	delete querydslDir
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('bootRun') {
	environment 'SPRING_CLOUD_CONFIG_URI', System.getenv('SPRING_CLOUD_CONFIG_URI') ?: 'http://34.50.50.170:13100'
	environment 'SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED', System.getenv('SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED') ?: 'false'
	environment 'DB_URL', System.getenv('DB_URL') ?: 'localhost:5432/chat-db'
	environment 'DB_USERNAME', System.getenv('DB_USERNAME') ?: 'pgsg-user'
	environment 'DB_PASSWORD', System.getenv('DB_PASSWORD') ?: 'pgsg-password-1234'
	environment 'DB_DDL_AUTO', System.getenv('DB_DDL_AUTO') ?: 'update'
	environment 'EUREKA_CLIENT_SERVICEURL_DEFAULTZONE', System.getenv('EUREKA_CLIENT_SERVICEURL_DEFAULTZONE') ?: 'http://34.64.58.121:8761/eureka/,http://34.64.104.174:8761/eureka/'
	environment 'EUREKA_SERVER_URL', System.getenv('EUREKA_SERVER_URL') ?: 'http://34.64.58.121:8761/eureka/,http://34.64.104.174:8761/eureka/'
}
