services:
  chat-service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DDL_AUTO: ${DB_DDL_AUTO}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      EUREKA_SERVER_URL: ${EUREKA_URL}
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
      SPRING_PROFILES_ACTIVE: local
      TRUST_STORE_PASSWORD: ${TRUST_STORE_PASSWORD}
      SPRING_KAFKA_SSL_TRUST_STORE_LOCATION: file:/app/ssl/kafka.server.truststore.jks
    volumes:
      - ./ssl:/app/ssl
    networks:
      - pgsg-network

networks:
  pgsg-network:
    external: true
