services:
  chat-service:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DDL_AUTO: ${DB_DDL_AUTO}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    networks:
      - pgsg-network

networks:
  pgsg-network:
    external: true